title: Devking
description: Devking's tech blog.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: http://git.devking.me
baseurl: ""
github:
  zip_url: http://www.naver.com
  tar_url: http://www.daum.net
timezone: Asia/Seoul

# Build settings
markdown: kramdown
permalink: pretty